In [29]:
import numpy as np

#making a matrix
myarr = np.arange(1,26)
mymatrix = myarr.reshape(5,5)
print(f"range: {myarr}")
print(f"mymatrix: \n{mymatrix}")

#multiplication
np.random.seed(1)
myarr2 = np.random.randint(1,21,size=(5,5))
print(f"random matrix: \n{myarr2}")
emult = np.multiply(mymatrix, myarr2)
print(f"element wise multiplication: \n{emult}")
dmult = mymatrix.dot(myarr2)
print(f"matrix wise multiplication: \n {dmult}")

#matrix addition
addmat = mymatrix + myarr2
print(f"matrix addition: \n{addmat}")

#summations 
sumcol = mymatrix.sum(axis=0)
sumrow = mymatrix.sum(axis=1)
print(f"printing summation col: \n{sumcol}")
print(f"printing summation row: \n{sumrow}")

#transposing 
tmatrix = mymatrix.T
print(f"printing transpose: \n{tmatrix}")

#splicing
print(f"printing middle 3x3: \n{mymatrix[1:4, 1:4]}")
print(f"printing row 2: \n{mymatrix[1]}")
print(f"prining col 3: \n{mymatrix[:,4]}")



range: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
mymatrix: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
random matrix: 
[[ 6 12 13  9 10]
 [12  6 16  1 17]
 [ 2 13  8 14  7]
 [19  6 19 12 11]
 [15 19  5 10 18]]
element wise multiplication: 
[[  6  24  39  36  50]
 [ 72  42 128   9 170]
 [ 22 156 104 196 105]
 [304 102 342 228 220]
 [315 418 115 240 450]]
matrix wise multiplication: 
 [[ 187  182  170  151  199]
 [ 457  462  475  381  514]
 [ 727  742  780  611  829]
 [ 997 1022 1085  841 1144]
 [1267 1302 1390 1071 1459]]
matrix addition: 
[[ 7 14 16 13 15]
 [18 13 24 10 27]
 [13 25 21 28 22]
 [35 23 37 31 31]
 [36 41 28 34 43]]
printing summation col: 
[55 60 65 70 75]
printing summation row: 
[ 15  40  65  90 115]
printing transpose: 
[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]
printing middle 3x3: 
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
printing row 2: 
[ 6